sudo cp controller.php /var/www/suitecrm/modules/CT_daily_status_report/
sudo cp ct_daily_status_report_entrypoint_handler.class.php /var/www/suitecrm/modules/CT_daily_status_report/
sudo cp tpls/*.tpl /var/www/suitecrm/modules/CT_daily_status_report/tpls/
sudo cp tpls/imgs/*.* /var/www/suitecrm/modules/CT_daily_status_report/tpls/imgs/
sudo cp views/*.php /var/www/suitecrm/modules/CT_daily_status_report/views/
sudo cp entryPointHandler.php /var/www/suitecrm/modules/CT_daily_status_report/
sudo cp subPanelHandlers.php /var/www/suitecrm/modules/CT_daily_status_report/
sudo cp css/*.css /var/www/suitecrm/modules/CT_daily_status_report/css/
sudo cp js/*.js /var/www/suitecrm/modules/CT_daily_status_report/js/
