name: suitecrm-test
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    networks:
      - main_network
    ports:
      - '${MARIADB_OUT_PORT}:${MARIADB_PORT_NUMBER}'
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_PORT_NUMBER=${MARIADB_PORT_NUMBER}
    volumes:
      - mariadb_data:/bitnami/mariadb
  suitecrm:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    networks:
      - main_network
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_PORT_NUMBER=${MARIADB_PORT_NUMBER}
    ports:
      - '${SUITECRM_OUT_PORT}:80'
    depends_on:
      - mariadb

networks:
  main_network:

volumes:
  mariadb_data: